
"""
Django settings for PT project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import sys
import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
sys.path.insert(0, os.path.join(BASE_DIR, 'extra_apps'))




SECRET_KEY = '28(^yf#l$%amtc#xu802u7o*+a5yc3n_oe#uhp1zj)ta$cg7qs'

DEBUG = True

ALLOWED_HOSTS = ['*']

#开启定义好的用户模型
AUTH_USER_MODEL = 'users.UserProfile'


#设置django-redis用来储存token
CACHES = {
    "default": {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        "LOCATION": "e:/python-code/PT/media/django_cache",
        # "OPTIONS": {
        #     "CLIENT_CLASS": "django_redis.client.DefaultClient",
        # }
    }
}


#restframework的配置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'apps.newtoken.mytoken.Authtication',#自定义token认证
        # 'apps.newtoken.mytoken.NewAuthtication',#自定义token认证
    ),
    'DEFAULT_PERMISSION_CLASSES':('apps.newtoken.permission.Mypermission'),#自定义用户权限全局设置
    'UNAUTHENTICATED_USER':lambda :"匿名用户",#未登录用户的user= none
    'UNAUTHENTICATED_TOKEN':None,  #未登录用户的token= none
    'DEFAULT_THROTTLE_CLASSES':('apps.newtoken.throttle.MyThrottle',),#自定义的节流控制  #####rest内置节流控制VisitThrottle
    'DEFAULT_THROTTLE_RATES':{'laoli':'6/m'},
    'DEFAULT_VERSIONING_CLASS':'rest_framework.versioning.URLPathVersioning',
    'DEFAULT_VERSION':'v1',
    'ALLOWED_VERSIONS':('v1','v2'),
    'VERSION_PARAM':'version',
    'DEFAULT_PARSER_CLASSES':('rest_framework.parsers.JSONParser','rest_framework.parsers.FormParser'),#定义数据解析器获取请求体中的数据
    "PAGE_SIZE":3,#分页参数，每页最多两条数据

    'DEFAULT_RENDERER_CLASSES': (
        #使用json rederer
        'rest_framework.renderers.JSONRenderer',
        #启用restframeworkAPI界面
        'rest_framework.renderers.BrowsableAPIRenderer',
    )
}

# 注册所有需要的APP

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'xadmin',
    'DjangoUeditor',
    'crispy_forms',
    'captcha',
    'rest_framework',
    'rest_framework.authtoken',
    'Paintings',
    'users',
    'corsheaders',

]

#django中间件列表
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ptdb',
        'USER':'root',
        'PASSWORD':'jianghan',
        'HOST':'localhost',
        'PORT':'3306',

        },
 }
# CORS_ORIGIN_WHITELIST = (
# '127.0.0.1:8000',
# 'localhost:8000',
# '127.0.0.1:8080',
# 'localhost:8080',
# '10.0.2.187:8080',
# 'taoduoduo-test.oss-cn-shenzhen.aliyuncs.com:80',
# 'ads-cms-api.aataotao.com:8000'
#
# )
#定义主url路径
ROOT_URLCONF = 'PT.urls'

#模板注册
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #模板路径
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PT.wsgi.application'




AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE ='Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

#静态文件url
STATIC_URL = '/static/'
#告知django静态文件路径
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS=[os.path.join(BASE_DIR,'static')]

#其他文件url
MEDIA_URL = '/media/'
#告知django其他文件路径
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')




"""邮件发送的配置"""

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_USE_TLS = False                           #是否使用TLS安全传输协议(用于在两个通信应用程序之间提供保密性和数据完整性。)
EMAIL_HOST = 'smtp.163.com'                     #发送邮件的邮箱 的 SMTP服务器，这里用了163邮箱
EMAIL_PORT = 25                                 #发件箱的SMTP服务器端口
EMAIL_HOST_USER = 'jianghanblog@163.com'        #发送邮件的邮箱地址
EMAIL_HOST_PASSWORD = 'laoli123456'             #发送邮件的邮箱密码(这里使用的是授权码)
DEFAULT_FROM_EMAIL = 'mail@tuweizhong.com'      #收件人看到的发件人
